Add database
vercel/next-learn pull request #153
Opened 2023-09-08 15:19 UTC by StephDietz

2023-09-11 13:06 UTC, delbaoliveira requested changes

2023-09-11 13:06 UTC, delbaoliveira commented on dashboard/15-final/app/lib/calculations.tsx
>  export const findLatestInvoices = (invoices: Invoice[]) => {
`findLatestInvoices`, this is another case where we can optimize using SQL, there's a rough comment above with how we can get only the last 5 invoices using SQL.

2023-09-11 13:06 UTC, delbaoliveira commented on dashboard/15-final/app/ui/invoices/table.tsx
> +
This component would also use SQL joins. So we query the customer name from the customer's table, based on the customer_id in the invoices table.

2023-09-11 19:30 UTC, StephDietz commented on dashboard/15-final/.env
> +POSTGRES_PRISMA_URL="postgres://default:IQA2FonHJi9d@ep-square-union-29037633-pooler.us-east-1.postgres.vercel-storage.com:5432/verceldb?pgbouncer=true&connect_timeout=15"
I _think_ so. This variable is added to the project when connecting the database, and the docs make it sound like we need it https://vercel.com/docs/storage/vercel-postgres/quickstart

2023-09-12 16:57 UTC, delbaoliveira submitted a review, later dismissed

2023-09-13 16:43 UTC, delbaoliveira approved these changes

2023-09-13 16:49 UTC, delbaoliveira approved these changes

2023-09-13 17:16 UTC, merged